---
- name: kubeadm init
  shell: kubeadm init --pod-network-cidr=10.0.0.0/8
  become: yes

- name: set up kubeadm for non-root
  shell: mkdir -p /home/aenglema/.kube
 
- shell: cp -i /etc/kubernetes/admin.conf /home/aenglema/.kube/config
  become: yes

- shell: chown aenglema:aenglema /home/aenglema/.kube/config
  become: yes

- name: kubectl apply
  shell: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml

- shell: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

#- name: get join command
#  shell: kubeadm token create --print-join-command
#  register: join_command_raw

#- name: set join command
#  set_fact:
#    join_command: "{{ join_command_raw.stdout_lines[0] }}"

